language: python
python:
- 3.8
- 3.7
- 3.6
install:
- pip install -U tox-travis
- pip install coveralls
before_script:
- black --check . || true
script:
- tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: YopX5a+01gwqyOT1zqTX4p2vLhccyBb9U4M0rx+kg+O+2MRFkGYXBD0Sv+/Qo1+anHKm41MfrKKhnl8EgxMgP30Ag0kK28kKR7MuHME4pfNI6EM2MMT/0JUpCJ00bRidBZplNm8P7yzF7J5eJF9u6c0ZPLl7UudoxOMx7xiqTFOxK23hxVib8SslqYNfVoHbjoBvoh6+Sr4mgLzvauy/7OfgIgHWUnH/h+kaREeczkuNpsA6OyeKbh50Wz6j5rhrhsM4JuDiGdRSw9oQjq4b8AxyBh+X4vUo8CBBEH4iwqCjR0KEF3x+CNGrOMZSzJHNOwo7aYEJWqqzAg2rAImiq3JOPmi3vTSWi2V+51Yz7VT7TeiPIsu8Cdw5PnwEIgsBT8bVR9uZZ1ktKyQ2P+6Dt8I86jQDbkKj3yJ7OCUxabUQ9hg++h0kuLd9Sw6dPaIYvGjqReaXsy7kB1NNEl1EsvWAGFCcuJAbCEpAcvJw0qU/+X5EnQ5Uqfvjy2lqqcvffZT69VQlbJFylIoped5st3x4Tfqbp+QhebQp1d4dBps00Kae99jdImYJjVWUA3e9s5YmxdAMC7HX60p6BppjDwhAlLrHyFu/zZvc2Y0zR7cDLC23vDpnbQQ8Wd7RxdqUs8KwTMFSqNohwbxfcnT2gt1MiAk2XU9s4mGMBjDBT3g=
  on:
    branch: master
    python: 3.8
after_success: coveralls
