language: python
python:
- 3.8
- 3.7
- 3.6
install:
- pip install -U tox-travis
- pip install coveralls
before_script:
- black --check . || true
script:
- tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: geqKfwrUSdUzGZcfAHrjX7lC8+kKfUFuVWwWgTL8qE5WBzu9Gx0oNgmwnNaQGiJG7msv9XiPCIxx0J8oYqdnhBFo6K1+2lD0WNLrzQjG8VcvDOHif4Ztr18Y6wVU4VGG6SVea1HHP7HIVZk4gmNkRd7W6p28KNgQCJF9aPVGYS1dVy31cvKH5dwF3sXdEmlQ+JRYrMhlbJJ+P2JcmtrKlZmSsPgMXavLLv8EX7ac44QqogJb9CoZJSlbrWaF3DkLe1BVaE5d4dKmD+u6oSPeJW8XTyN02sUrqNGAokt8huws8FMiCZC8bAwbPWaBiUiBMzuilJuBKJFJTjZLw4yWRlLBViKQAEfZWAI7IDk1i5m+iL9fk3Hmi0+CiSplE5dpdEXOdzZ9jnfpXCnrEk1zfPi2FTjMqNKHfKG3Wi5ibs5KA07hIZFaAhbIlvsmCjlg3GKENeQaO0d3+p0O+EmkxvdOyZBS3VIcEjb/TxN+agrc/VAA3wMg1UOQo/0XfhjdPR17QO9wcvv1SHKeOJoJP/iyv3zON6BbyLKIxob/OwDCD+L7dIQPPC3Er8P2h4aMLaKo3w1pPeFfH4EFgjN6oH4ZMJPXkUIGRF7v2VSWcpfAL5PxytCJD5yW8KUp55jQITAwWjanat7vYuaVkSUbiD80z3LUNnmuYMS8qPC3rao=
  on:
    tags: true
    repo: axelschmidt91/clt_py
    python: 3.8
after_success: coveralls
