language: python
python:
- 3.8
- 3.7
- 3.6
install:
- pip install -U tox-travis
- pip install coveralls

before_script:
    # run black to check if some files would need reformatting
    - black --check . || true
    # stop the build if there are Python syntax errors or undefined names
    - flake8 . --count --ignore=E501,E402 --show-source --statistics
    # - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
script:
- tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: axelschmidt91
  password:
    secure: N3K7j3jIOISRwWd2W0XFLeMt0lKlw/4JXK9VWtVrAdQ09j5kmFPl97UGcdA7k1LVRplm7VahnmZHmIH8hbXwHti6vUIm4AXsdiKBb4F9dpurPr74kbUyNcEkils7pl/ZgKb0IyLiSjIaq6KutCslnfOcZ4dL/lhy2CxADrepMkm1dg9epRnwCsujcu19W+j2vKbFUNzUNCqWVLdpByW3zcHKdYkxuAqy05EqPL8a/8228eLkKR8XLMZvh0dq/O869H/4CP9C6yf7u0Tw9N6o9hfX7uLG5oeXSZQEq8Vuf6TkgNwmqnd1iRWnPta5eOlTLfY0Qnbh4haUOB3zjTyKfGojp/hGDT8p6oK8uWPtZQAb1OT83WUH9JpnGCIt56nJlzA3RLTJjwsUMiDzlIApRy1vDCguPjYmcHd88APUrw4rmCAjrpxutEBay04FrGI7+nLNI+R93OAKCG1FHuacH5qmn/YRVYPWSy34oZS64l9UMTeSZy01EsWEgeOXq9ns4gi1B5ljYuafIG8kGdtCnabxAK8YBhhalUxW7N3lVsNk1gzGy15EhNwKtwjdNVeRpOTbyrFyr7vWhxv8Vb5qEY0+xfaao3nmjQ8x1SlSuyGIRLL78Y9wAKItA1hcNsASXZ3vCiOl9OvgQ+LlLCytHdjaEI+wBL+3AyXW45oHOhk=
  on:
    tags: true
    repo: axelschmidt91/clt_py
    python: 3.8
after_success: coveralls
