language: python
python:
- 3.8
- 3.7
- 3.6
install:
- pip install -U tox-travis
- pip install coveralls
before_script:
- black --check . || true
script:
- tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: aTeBS/Ws6qrukiTV2rssqL9w0mxBYySnj1NWKEbyKDasXEy72YBVI1oUDMzLcRf0Jgbjt8Kd+m2lijcaqu116YHTLa0tIE60DrOt2R+9ynCvtgGz2YDEoJ3C1947IqFH+X56lUzGrTOX6j6+BtU38tphsjSZM46swHtNvteX8OnjmMMfKYsRelFiQ4TdBTQ3TI6fH7sIVGsepjkY4BsXB9fGT6BINdRgtbNNnZjTBHnBdsZvrHO+31ALot2eummtZEkLpa9uzbTdaa4LMWNZShfBXtnRH+ACo2713TWEKs52eG+V/Y4KsqSaXsWcIp4y7hon8i1DNDx3f+2vyPKX3S67csEUE+pz0bl1wMlaOnDpav2ERxHwR/NY+xPyOiPLJZpnwP2aSjUAQEOfD3TPfb6TgdLc37LUJL9GNWok2IHQLUNtztq76rQ1GuRVJMKZAabP2umPbGVsO1jaEZR7Owdo0iujrQWvViEAM+W5QKA2VaQsqpnsLfWbvkWyMgkXqcN+EfiSauG5PeKanyMTv5cVxmvZBWGWEv75aTnpQaL47aCjTCIUDlrDKbXDP2YHXLJK7S78bY0g7aaQrISM0m5U1NfvxMGl/lChasEUalK2pp/2ewn9ud1Jg0zXBlCA2jwHyxxwgLSiwfX+yFY0k6wCus0XffewGVUofWKReCc=
  on:
    branch: master
    python: 3.8
after_success: coveralls
