language: python
python:
- 3.8
- 3.7
- 3.6
install:
- pip install -U tox-travis
- pip install coveralls
before_script:
- black --check . || true
script:
- tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: '09aiSOXWok/KPsUDKtZr1e6OFhWRP1SnJHSYJQddesbtnuMbFukM5gbSVGS4RebJaP50nandBfSyRm5UrCwee1sTf1n9Fb0ToCZS1dRcUHGQpazqLM6ewnTLGHKZlLwRlqsVZ+ngnw89zN9YCGwjahmwsFBBFfD24KUX/Kx+jzGh5Z7SX7zdij9PqICuHGgvXh4CQwsZ27Xz3NvJifplp+blMhqHSo1oZRHeqWPs00oijkf4XJBrtk0L+LxefzbWF8KD4Ksxen7M6wrdrZ0PeHBTMpYnZ3kfaU5CUPMo9TGlYtNj/+PGnk7aFrKRb3FFuw6mt+OEvE6xBmNLu4ro3SKvh2atGE4qEv0HWwRVdloR0QoPpMvwKrYpq6Iav0bH9VSGRFw+beaccTR5eeRkdy177nPvrq83BiNHmwXFTF1LAE8GgtnHp/BmtVV24lqMTIqo/gSY3HwgyDf8KkNSnHRAPgLF5IJRHkTnKz4jM4LAfAoP99foMITxRkMbDPaum0cJZt6kNOzCshN++GPQ9uEF/wj0zVw9cu2Q8B3aFyHv4ry9np0w3L8VquYKzeGlU9biBAoQxp0tNNinaU2nA7/tAbZ3ucX0MZN4HPWOrstg9NJR+AyzB9n2lmW+xcjZ7XdnkWw9pIpiVhgMPGECXxtwmE8NTsdfHXmTuQ2Pd+o='
  on:
    branch: master
after_success: coveralls
