language: python
python:
- 3.8
- 3.7
- 3.6
install:
- pip install -U tox-travis
- pip install coveralls
before_script:
- black --check . || true
script:
- tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  passwort:
    secure: f/SJb/p8YmK38Mycv3BFZbAOg+L4VTUT33BHTG3CwWW/VWXG9yCCHpa7MT5dBWSll3bsbNfCEB/srAVvOasAjgklGias4F1biWSP254yNhk3Q+41wPKfGs17qDOPXDhjF7uvAUSFnbLvcjioJ/M56ygbH8DvuEactaYhuCw0rdGxsBWbeweD4HR1JGO2TxZwn4BtgmZh5saY7WNx4+nuMeD00SQ+bkFTGmyS+eUlrXQDEFkqinSy0oqmSeYeZ5berOFSsJ6SkrrtzXsMWDhCPSWhvHsDgsAIcLnStKtDBa7y2++2z/CVyr5S737No+Yzy09hpN4B1WsZzwd1OXjwVeDeGrvvjHVPPKbQkDl123c4LniveMMvov0fyv2veq2YK+XEN3mWSz+L5bBOEcB6Z6z4Rdme1wlcNkE+cXWjY6w052ohAjf9a1fwp4YrZnTiebzUJAEMVbfMbVOqaviiR2Kl22K1oaQsctQ3FqMwutKUURwuVt++WK+acPc9cAoDLLEqB48OYqRVvRk6ytUP4JYfuBfVZqI3INlQfivlEnWW57si2+3ekph4bm/vtvqyhYvpSFSE2g5ExEoROu3/ebt408R6dp0+kaub3446Gm1FUc0IqxTgSfKbAeL243WLaVu27Lx1/P/jut47s71uY9kNJ9tqJxRqGNhnhZuNIic=
  on:
    branch: master
    python: 3.8
after_success: coveralls
