language: python
python:
- 3.8
- 3.7
- 3.6
install:
- pip install -U tox-travis
- pip install coveralls
before_script:
- black --check . || true
script:
- tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: axelschmidt
  password:
    secure: eRYQGei7nP/WelVELMsi5XzF2LZrxtJuVnxstY3DPeYG7eiAU3kaLW/dgGzm/XsZZmEmVECS8AwEzEHvOMUmozVKZQmXA8SUms3WXI6GLT7uq5aJVRjKQkcvnYj1K/ev7eJyd7y+DQCsn1MEP9tkd1mZ4vIGlpuKSACWNyKk9YozOJOQ0U17IamoUphROq4y6v1QIdPfdXLATLLRLxI1lai5OGmej0dY6Rheh7OtzDjyPVYgMWC7dbFkxE6emEMxwn4FZGaYEs8/hNfCXCqC/LUFfkQetY+cKX5qLnwhy5EdOTyHeZrhQv1gZTAvHXE3iAOPyvbo0E/oAaDAp1rCxhmoUA7NYyZqbS555Tzty+Qnyx7A75nnrlmB1lutVUkVDxMXcK046wQ37KFCs24qg7A/yWXSFelsZaolkqh8oilh9Y93hPa6nMbR92Fzm2quuKdHFPqr0bGHYuRcLdS9qhRsoNokZA91jp1MdM9TV9MMhzP5eoUlYhImoQzULEjgndXRObAHnyPV8XgtrcUONhiE4IfQ+gGkFUIZPJT8t5FRQSEkhIu9ZCsmb+rmqBSaRkJr80qY4iQEm6AGLWCtyYsL+29grMWOJ4N4UhNO5faLEhux0t4IrjB8KwlHEJ3DKNn07ET1KpmPytyHHemaattW/+v9bqNIY6pi1xe9TL8=
  on:
    branch: master
    python: 3.8
after_success: coveralls
