language: python
python:
- 3.8
- 3.7
- 3.6
install:
- pip install -U tox-travis
- pip install coveralls
before_script:
- black --check . || true
script:
- tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: egypUqci1uBe6oTh0xH6PyXIp129QuxwoCILVVrsLNMWkMUaRh0++2yeHrqCMjzUYb2a6jTkpHPJZN8dHOyhCvK5hcEzD5V1vHsZxx+RGLX8NG2laG1+4Dicp5vDj/pBOfqBpBJH5whrNSA5+4uqXhtZcFTY1SXEzKkieHt9ZmNFU8cKOHY5dOLkXSN0EtdTYvqOUWid6iCZQiHjE3SXrIRy/1rtnrdRtIza/bwn7fv/f5jEvixqfMFAnys3hZVlsJJNSAA1E2XwxPQNqgNa2o0XqJAxs6OGhk4J3xQSszPe8yQV5GMPENzOkVtbeei7/LAKfjL7/u3tBvWqZ+wG0mOrzeRqkYCRAvfOLRX9fQgTARPyJAj7a3UJxvsCLTjml67vRMx8NEjefJFLriL3mp5MkLvEX/cB8//QpUHifu9tid5gegeEyvrBAMCdJKC+ksv2aGHA5krfY8IX1UMr6gUqXt2w043vGFRivkLqsuM+IE8K56heYsMEhXyKi6LJPtjXkNF3HQXCpG5hYZu1zRU+UR+bgkDmukhPfgX9KJdjPClBJDnMuTWwJb9Ydz/uh6A1WfwtJB+EXA4JgaWeqpojCc3CY66KCKK0t5ukItSVcOhsubsmqNDhqWIEml+yaKBj6C8ZzgsQo+o6OpCadF7ln10JKLjDvsaoU8Vi9yg=
  on:
    branch: master
    python: 3.8
after_success: coveralls
